name: 'Determine Swift Destination'
description: 'Determines the destination string for Swift builds based on the target platform and device'

inputs:
  platform:
    description: 'Target platform'
    required: true
  device:
    description: 'Target device for simulator'
    required: false
    default: 'iPhone 15'

outputs:
  dest:
    description: 'The destination string'
    value: ${{ steps.dest.outputs.dest }}

runs:
  using: 'composite'
  steps:
    - name: Determine destination
      id: dest
      shell: bash
      run: |
        # Normalize platform string (remove quotes, trim whitespace)
        PLATFORM=$(echo "${{ inputs.platform }}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
        DEVICE="${{ inputs.device }}"
        
        if [[ "$PLATFORM" == "macOS" ]]; then
          dest="platform=macOS,arch=arm64"
        elif [[ "$PLATFORM" == "iOS Simulator" ]]; then
          dest="platform=iOS Simulator,name=$DEVICE"
        elif [[ "$PLATFORM" == "tvOS Simulator" ]]; then
          dest="platform=tvOS Simulator,name=Apple TV"
        elif [[ "$PLATFORM" == "watchOS Simulator" ]]; then
          dest="platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)"
        else
          # Fallback to generic for build-only scenarios if not a simulator
          dest="generic/platform=$PLATFORM"
        fi
        
        echo "Determined destination: $dest"
        echo "dest=$dest" >> $GITHUB_OUTPUT
