#!/bin/bash

protected="master"
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

# Prevent from commiting to master branch
if [ $current_branch == protected ]
then
    echo "$protected is a protected branch, please create your own branch and use PR."
    exit
fi


# To prevent debug code from being accidentally committed, simply add a comment near your
# debug code containing the keyword !nocommit and this script will abort the commit.

if git commit -v --dry-run | grep '!nocommit' >/dev/null 2>&1
then
  echo "Trying to commit non-committable code."
  echo "Remove the !nocommit string and try again."
  exit 1
else
  exit 0
fi
